CREATE TABLE IF NOT EXISTS menus (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name TEXT NOT NULL,
    price FLOAT NOT NULL,
    category INT NOT NULL,
    image INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);